void intro()
{
cleardevice();
//clrscr();
 settextstyle(8,0,1);
     outtextxy(250,50,"..Introduction..");
      settextstyle(2,0,4);
      printf("\n\n\n\n\n\n\n\n\tGraphical Representation of Stack and Queue represents the Data");
      printf("\n\n  Structure concepts.\n\n\n");
      printf("\n\tA stack is a container of objects that are inserted and removed");
      printf("\n\n  according to the Last-In-Last-Out (LIFO) principle\n\n\n");
    printf("\tA queue is a container of objects(a linear collection) that are ");
     printf("\n\n  inserted and removed according to the to the Last-In-Last-Out (LIFO)\n");
     printf("\n  principle\n\n\n");

//printf("HI");
//clrscr();
//printf("dfsF");
getch();
cleardevice();
}
